POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "John Smith",
    "dateOfBirth": "1976-09-09",
    "ssn": "123456-123A",
    "gender": "male",
    "occupation": "blacksmith"
}