POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: 

{
    "title": "Otsikko",
    "author": "Kirjoittaja",
    "url": "Osoite",
    "likes": 5,
    "userId": ""
}