POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer

{
    "title": "Otsikko",
    "author": "Kirjoittaja",
    "url": "Osoite",
    "likes": 5,
    "userId": "6864204ee0c19930cd2401f9"
}